### ISSUE TITLE
Log warnings

### ISSUE THREAD

**Issue by seancarr26** [fiskaltrust/product-de-bring-your-own-datacenter#15]
`warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]`
      Failed to determine the https port for redirect.

I assume this can be ignored?

```
warn: fiskaltrust.SignatureCloud.DE.Services.HelipadUploader[0]
      Failed to remove queue upload for cashbox cashbox. cashboxid: ************
```

I assume this is just the pods ensuring that there is only one active cashbox in the cluster and can be ignored?

**Comment by volllly** [comment]
`warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]` ist just saying that the `byodc` pods are using https. This is not a problem since https is handled by ambassador (see [HTTPSReference](https://github.com/fiskaltrust/product-de-bring-your-own-datacenter/blob/master/HTTPSReference.md)).

```
warn: fiskaltrust.SignatureCloud.DE.Services.HelipadUploader[0]
      Failed to remove queue upload for cashbox cashbox. cashboxid: ************
```
This has to do with the receipt upload to the Portal. You should see the receipts you signed in the ReceiptJournal `https://portal-sandbox.fiskaltrust.de/Queue/ReceiptJournal/<queueId>`.
