### ISSUE TITLE
What is the importance of Redis in the cluster?

### ISSUE THREAD

**Issue by freakmaxi** [fiskaltrust/product-de-bring-your-own-datacenter#28]
In the Kubernetes cluster, there is a Redis pod running. Can you explain the importance of this Redis pod and how critical its usage and does it requires having a Redis cluster for better failover handling? Should we concern about its health?

**Comment by fiskaltrust-ckr** [comment]
Thank you for this question.
Basically, the redis instance is to keep all the Backend PODs in sync. There is a lock mechanism, which ensures that every cashbox keeps being a singleton. So if you loose the redis instance, redeploy it and restart the backendpods.
The worst you may lose is the current sessions.
If you would like to build a redis cluster instead of a single instance depends on your availability design. You could also consider using a PaaS Redis if you use Public Cloud Services.
BR
Christian
