### ISSUE TITLE
Failed to acquire lock after 00:01:00. Timeout

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/product-de-bring-your-own-datacenter#49]
**Describe the bug**
We see an increased number of Redis Timeout exceptions which are not related to pod restarts. 

`
System.TimeoutException: Failed to acquire lock after 00:01:00. Timeout\\n         at fiskaltrust.SignatureCloud.DE.Services.Locking.RedisLockService.ProcessLockiningAsync[T](String lockName, Func 1 executeMethod) in
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**STDOUT/STDERR**

`
9:50
{"id": "36212614997347399125404144454156738234561626347393646592", "timestamp": 1623829817119, "message": "{\"log\":\"\\u001B[41m\\u001B[30mfail\\u001B[39m\\u001B[22m\\u001B[49m: Microsoft.AspNetCore.Server.Kestrel[13]\\n      Connection id \\\"0HM9GHEDFGSMT\\\", Request id \\\"0HM9GHEDFGSMT:00000002\\\": An unhandled exception was thrown by the application.\\n      System.TimeoutException: Failed to acquire lock after 00:01:00. Timeout\\n         at fiskaltrust.SignatureCloud.DE.Services.Locking.RedisLockService.ProcessLockiningAsync[T](String lockName, Func`1 executeMethod) in /src/src/fiskaltrust.SignatureCloud.DE/Services/Locking/RedisLockService.cs:line 36\\n         at fiskaltrust.SignatureCloud.DE.Controllers.SignController.Post(ReceiptRequest request) in /src/src/fiskaltrust.SignatureCloud.DE/Controllers/SignController.cs:line 102\\n         at lambda_method13(Closure , Object )\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\n         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\\n         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\\n         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\\n         at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\\n         at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\\n         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)\\n\",\"stream\":\"stdout\",\"docker\":{\"container_id\":\"7e00f6edf4f368b147e809c950c5538519a206b4848402aafb78bb5d3380f0a8\"},\"kubernetes\":{\"container_name\":\"byodc\",\"namespace_name\":\"bring-your-own-datacenter\",\"pod_name\":\"byodc-77cdc8cf66-8pbdk\",\"container_image\":\"ghcr.io/fiskaltrust/byodc-mysql-fiskaly:1.3.16-buster\",\"container_image_id\":\"docker-pullable://ghcr.io/fiskaltrust/byodc-mysql-fiskaly@sha256:7443476fc54d0f2233758b9bd499ddf660b7fe35d27cb3d049c33b565cc6f271\",\"pod_id\":\"c42db78d-d92d-4060-8789-f622b8128221\",\"host\":\"ip-192-168-153-146.eu-central-1.compute.internal\",\"labels\":{\"app\":\"byodc\",\"pod-template-hash\":\"77cdc8cf66\"},\"master_url\":\"https://10.100.0.1:443/api\",\"namespace_id\":\"55e764f3-dcc1-456b-a56a-02b4edd83cd7\"}}"}
`

**POSSystem (please complete the following information):**
- 46a60bc4-42f6-4a95-b758-77c8da74f203

**Cashbox Information (please complete the following information):**
 - 79cfcecf-3a7b-4e34-90be-bc3e322dc176 (a single example only but involves multiple cashboxes )

**Additional context**
We don't see any high load on the cluster, about 20 requests per minute at max

The redis instance is quiet but we do see a spike in the number of items which drops at around 8am UTC 

<img width="454" alt="Screenshot 2021-06-16 at 17 09 59" src="https://user-images.githubusercontent.com/34276999/122246132-97c44180-cec6-11eb-9e0b-3407646dd18b.png">

We don't see a huge increase in the number of workers created during that time, here is the search in the logs for "Worker created" text (the times here are UTC+2: 
<img width="1246" alt="Screenshot 2021-06-16 at 17 14 12" src="https://user-images.githubusercontent.com/34276999/122246547-ed005300-cec6-11eb-8fa2-a06516407551.png">

Our Setup: 
10 pods with limits: cpu: 1, memory:  1536Mi handling over 700 cashboxes, and we don't see any restarts or any of the pod getting close to their limits when the issue happens

Each of salons would be generating a 'Daily Closing Receipt" first thing in the morning so my suspicion is that it's related to that. It's hard to know what's causing it without knowing how the pods work internally in terms of those redis locks.

**Comment by darek-phorest** [comment]
we noticed that when the issue happens on prod at the same time it also happens in our dev environment which talks to dev fiskaltrust portal, the issue stops right after fiskaly http timeouts are thrown on prod, our dev and prod are separated on our side so it looks to me that fiskaly is struggling handling the uploads

`
Fiskaltrust.Middleware.Localization.QueueDE.SignProcessorDE[0]
Failed to export TAR file from SCU.
Fiskaly.Errors.FiskalyHttpTimeoutError: HTTP timeout
at Fiskaly.FiskalyHttpClient.ThrowOnError[T](JsonRpcResponse`1 response)
at Fiskaly.FiskalyHttpClient.Request(String method, String path, Byte[] body, Dictionary`2 headers, Dictionary`2 query)
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
`

**Comment by TSchmiedlechner** [comment]
Hi @darek-phorest, 
thank you very much for reporting this and all the provided details! Our first investigations hint that the Redis lock timeout is caused by the "more inner" fiskaly timeout, which is thrown by the SCU (as you correctly observed). After checking our internal monitoring, we noticed that several fiskaly timeouts are occurring at the timeframes the issue is occurring for other Cashboxes as well.

Additionally, a second partner reached out to us with the exact same issue yesterday, so it seems like it's not directly related to your usage of BYODC/the type of requests you send.

We will investigate this and also reach out to fiskaly to get some more insights into why the timeouts are occurring (maybe the test systems are throttling connections or something similar). 

We will get back to you as soon as we've got any results - again, thank you very much for the detailed error report!
Enjoy your weekend 🙂

**Comment by darek-phorest** [comment]
hi @TSchmiedlechner , thanks for getting back on this, here is one extra piece of information that might be helpful for fiskaly to investigate the issue, from our side it looks like the issue started happening on Tuesday morning: 15.06.2021

<img width="881" alt="redis_locks_increase" src="https://user-images.githubusercontent.com/34276999/122559347-7fc3fd80-d03f-11eb-8152-8fac622f2850.png">

**Comment by matthiaskrumpholz2** [comment]
Hi @darek-phorest @TSchmiedlechner ,

i think that we are the second partner who had exactly the same issue ;-)
We also had the issue the first time on Tuesday. Maybe there was a change on the side of fiskaly?

![image](https://user-images.githubusercontent.com/31626316/122984798-b41c1e80-d39d-11eb-894b-9f3d628ef8f6.png)

We currently fixed it with a workaround. We do the export in the late evening instead of the first request in the morning. But it could not be the end solution.

Best,
Matthias

**Comment by darek-phorest** [comment]
@TSchmiedlechner any feedback from Fiskaly on that ? Things seamed to have improved this week and we would like to understand if it's something Fiskaly did or that Mathias team moved their exporting requests to the evening.

Thanks
Darius

**Comment by TSchmiedlechner** [comment]
Hi @matthiaskrumpholz2 and @darek-phorest,
sorry for not getting back earlier, we tried to investigate a bit more ourselves at the end of last week and had the following findings: 

After some inactivity, requesting open transactions from a TSE takes quite a while (up to one minute). As we do this while running a daily-closing receipt, this can lead to timeouts given the default maximum request time of 50 seconds.
The following calls are fast as usual - I assume that your workaround "solved" the problem because the affected TSEs are already cached in the evening on fiskaly's side. As we've reproduced this behavior with Postman (bypassing all clients), it might be specific to the API. 

We've opened a ticket at fiskaly containing these details and will get back to you as soon as there are any updates. Meanwhile, thanks for your patience and for the hint about the workaround, this helped a lot narrowing down the problem!

**Comment by TSchmiedlechner** [comment]
Some additional hint: it's technically possible to increase the timeout we use for the fiskaly HTTP calls by setting the SCU parameter  `FiskalyClientTimeout` (in milliseconds, default: `50000`). Personally, I'd only do this as a last resort though, I'm optimistic that we can find a better solution together with fiskaly.

**Comment by TSchmiedlechner** [comment]
Hi again,
we got some feedback from fiskaly yesterday: According to them, this behavior might be expected when requesting transactions with some filters (as we do it). They also mentioned that they're working on the performance of their API, and that the upcoming `v2` (which we anyway need to switch to, as it's the certified version) will definitely show improved performance characteristics.

Would it be okay for you to continue using the workaround until then, and maybe continue investigating together with fiskaly if the issue persists with the new version? According to the official roadmap, it should be available in production by the mid of July (altough it might take as a few extra days to finalize our implementation).

**Comment by darek-phorest** [comment]
Hi @TSchmiedlechner 
i would be willing to say that this issue may not be related to Fiskaly but i am not sure. The reason i am saying that is that the redis key should be removed when the timeout occurs, so by default it's 50 seconds from your above comment, but we can see that the key in redis persists for much longer, it could be up to 2 hrs (if you take a look at the graphs above you can see that) . If it's only the first requests for the queue that hangs then after the timeout the subsequent requests should be fine. In this case we don't understand why the key in redis is persisted for so long. Switching the "Daily Closing" to the evening is not a trivial task for us, is there some other fix for this that we can apply?

**Comment by darek-phorest** [comment]
Hi @TSchmiedlechner any reason why the Daily Closing is locking for so long and then blocking normal purchase transactions? Is the Daily Closing doing a retry multiple times to Fiskaly which hangs and therefore causing a lock for so long ? When we remove the key it's reinserted after short time without issuing any new receipts so there must be a process in the pod that does that

Thanks

**Comment by darek-phorest** [comment]
@matthiaskrumpholz2 we started seeing the locking also happen in the afternoon, does that happen for you also?

**Comment by Solrosy** [comment]
Any news on this one, guys?

**Comment by TSchmiedlechner** [comment]
Hi, sorry for not getting back earlier, holiday season hit us hard..
I think it might make sense to discuss the issues you're experiencing in a call to hopefully unblock you, I'll reach out to you to organize something. I'm still quite convinced that the issue is originally caused by the long request time, but you're right, it might be leading to other issues afterwards that we've not yet fully caught.
